### ISSUE TITLE
[Touitomamout] Tweets not syncing

### ISSUE THREAD

**Issue by eudemocracystiftung** [the-convocation/twitter-scraper#113]
Hi,
We are using the twitter-scrapper via Touitomamout and are encountering this issue: https://github.com/louisgrasset/touitomamout/issues/241

Basically, the content-mapper does not find any tweets. So the whole process goes smoothly with no error messages, but nothing gets synced. 

Any ideas?
Thanks!

**Comment by karashiiro** [comment]
Not sure if this is the issue or if there are multiple separate issues right now, but I ran the scraper tests just now and couldn't log in:
```
    Unknown subtask ArkoseLogin

      109 |         next = await this.handleSuccessSubtask(next);
      110 |       } else {
    > 111 |         throw new Error(`Unknown subtask ${next.subtask.subtask_id}`);
          |               ^
      112 |       }
      113 |     }
      114 |     if ('err' in next) {

      at TwitterUserAuth.login (src/auth-user.ts:111:15)
      at Scraper.login (src/scraper.ts:410:5)
      at getScraper (src/test-utils.ts:55:5)
      at Object.<anonymous> (src/tweets.test.ts:331:19)
```

The login flow involves a bunch of task messaging back and forth, and I haven't seen this task name before, so it's possible that the login flow changed, in which case a bunch of APIs will stop working. Still need to figure out how exactly this changed, though.

**Comment by karashiiro** [comment]
Still looking into it, but I'm not sure how soon it can be fixed, since I haven't deciphered the new login flow yet.

I'll be out of the country for a few weeks so I don't have much time to work on this before the end of the year — hoping I can figure this out within the week.

**Comment by karashiiro** [comment]
Actually, when I tried debugging this just now, I logged into the account I was using for unit tests to compare against the real login flow for that particular account. It was the same as what it had been before it broke, and then when I ran the unit tests again they all worked as expected.

I wonder if this means this issue was some kind of suspicious account check, and logging in through the website cleared it? At any rate, there doesn't seem to be any new fundamental issue with the scraper. I do still want to understand why this alternate auth path happened before I logged in on the website, though.

**Comment by karashiiro** [comment]
So as for next steps, I suggest manually logging into your scraping account once and seeing if that magically fixes things.

Ideally, when you do that, log in from the same geographical region (or IP if possible) as your service to avoid accidentally tripping any anti-phishing systems.

**Comment by karashiiro** [comment]
Oh, I just reread the touitomamout issue, this happens with a guest login as well. Possibly a separate issue here, then.

**Comment by karashiiro** [comment]
I just ran the repo's CI action and saw the same issue there ([logs](https://github.com/the-convocation/twitter-scraper/actions/runs/12332359305/job/34420082071)), which is another point in favor of this explanation. The anti-phishing checks weren't this strict before, so they might've locked things down even more strictly recently.

**Comment by karashiiro** [comment]
I went ahead and cloned touitomamout to try and get a better understanding of what's happening, and I'm fairly certain this is either an issue on their end (either a bug or more likely a documentation issue).

Dropping a breakpoint [here](https://github.com/louisgrasset/touitomamout/blob/b08e7b5f73f8c3a9146952f80462838aade04e12/src/services/tweets-getter.service.ts#L53) (and enabling sourcemaps from Vite) shows that the scraper is able to retrieve tweets, it's just that `getEligibleTweet` is returning `undefined`, signaling that everything in your account was filtered out. [This](https://github.com/louisgrasset/touitomamout/blob/b08e7b5f73f8c3a9146952f80462838aade04e12/src/helpers/tweet/get-eligible-tweet.ts#L17) is the line of code that determines whether or not a post is replicated - breaking it down, it roughly means:
1. The post must not be a retweet.
2. The post must not be a common on one of your own posts.
3. The post must not be a QRT of one of your own posts.
4. The post must have been made in the past 3 weeks.

**Comment by karashiiro** [comment]
Copied the comment to the original issue for tracking purposes

**Comment by danbednarski** [comment]
Experiencing a similar problem with https://github.com/ai16z/eliza-starter.

I ran the project with valid Twitter credentials and crash with the following error:

```
Error: Unknown subtask ArkoseLogin
    at TwitterUserAuth.login (file:///Users/danielbednarski/Documents/eliza-starter/node_modules/.pnpm/agent-twitter-client@0.0.13/node_modules/agent-twitter-client/dist/node/esm/index.mjs:351:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Scraper.login (file:///Users/danielbednarski/Documents/eliza-starter/node_modules/.pnpm/agent-twitter-client@0.0.13/node_modules/agent-twitter-client/dist/node/esm/index.mjs:2280:5)
    at async _ClientBase.init (file:///Users/danielbednarski/Documents/eliza-starter/node_modules/.pnpm/@ai16z+client-twitter@0.1.4-alpha.3_@google-cloud+vertexai@1.9.0_@langchain+core@0.3.25_opena_5krollsqbthh335txyixvqmavu/node_modules/@ai16z/client-twitter/dist/index.js:1015:7)
    at async Object.start (file:///Users/danielbednarski/Documents/eliza-starter/node_modules/.pnpm/@ai16z+client-twitter@0.1.4-alpha.3_@google-cloud+vertexai@1.9.0_@langchain+core@0.3.25_opena_5krollsqbthh335txyixvqmavu/node_modules/@ai16z/client-twitter/dist/index.js:1377:5)
    at async initializeClients (file:///Users/danielbednarski/Documents/eliza-starter/src/index.ts:132:32)
    at async startAgent (file:///Users/danielbednarski/Documents/eliza-starter/src/index.ts:189:25)
    at async startAgents (file:///Users/danielbednarski/Documents/eliza-starter/src/index.ts:211:13)
```

Other users report the same problem. Happy to help debug this and provide any additional info which may be useful.

**Comment by karashiiro** [comment]
Creating #114 for that as it's a separate issue.
